import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Footer from "./components/Footer";
import { Providers } from "./providers";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`pt-24 bg-magnolia h-screen ${ubuntu.className} bg-[url('/images/bg-sidebar-mobile.svg')] bg-contain bg-no-repeat bg-top`}
      >
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
